// <auto-generated />
using Marketplace.Infrastructure.Shipping.OrderPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Marketplace.Infrastructure.Migrations.OrderDb
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20220209223208_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Marketplace.Infrastructure.Shipping.OrderPersistence.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanceledById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Shipping.OrderPersistence.Status", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = "ae10037d-d29a-4052-9af7-08587b0e8ae3",
                            Name = "Delivered"
                        },
                        new
                        {
                            Id = "bb619c5d-711d-4143-aea7-02e95039295d",
                            Name = "Shipped"
                        },
                        new
                        {
                            Id = "61a45093-586f-4e0a-ab25-75ed09177002",
                            Name = "Processing"
                        },
                        new
                        {
                            Id = "f5039077-6cc9-4292-8068-1ee030d10394",
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Shipping.OrderPersistence.Order", b =>
                {
                    b.HasOne("Marketplace.Infrastructure.Shipping.OrderPersistence.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
