// <auto-generated />
using Marketplace.Infrastructure.Sales.BuyerPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Marketplace.Infrastructure.Migrations.SalesBuyerDb
{
    [DbContext(typeof(BuyerDbContext))]
    [Migration("20220214195022_intialMigration")]
    partial class intialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Sales.Buyer")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Marketplace.Infrastructure.Sales.BuyerPersistence.Buyer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Sales.BuyerPersistence.Offer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuyerId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("BuyerId1");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Sales.BuyerPersistence.Offer", b =>
                {
                    b.HasOne("Marketplace.Infrastructure.Sales.BuyerPersistence.Buyer", null)
                        .WithMany("AcceptedOffers")
                        .HasForeignKey("BuyerId");

                    b.HasOne("Marketplace.Infrastructure.Sales.BuyerPersistence.Buyer", null)
                        .WithMany("PendingOffers")
                        .HasForeignKey("BuyerId1");
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Sales.BuyerPersistence.Buyer", b =>
                {
                    b.Navigation("AcceptedOffers");

                    b.Navigation("PendingOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
