// <auto-generated />
using System;
using Marketplace.Persistence.Browsing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marketplace.Persistence.Migrations.BrowsingDb
{
    [DbContext(typeof(BrowsingDbContext))]
    [Migration("20240702212912_RemovedOwnedManyEntitiesMigration")]
    partial class RemovedOwnedManyEntitiesMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marketplace.Persistence.Browsing.CategoryEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.SearchEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SearchEntity");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.ViewEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SearchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SearchId");

                    b.HasIndex("UserId");

                    b.ToTable("ViewEntity");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.ProductEntity", b =>
                {
                    b.OwnsMany("Marketplace.Persistence.Browsing.ImageEntity", "Images", b1 =>
                        {
                            b1.Property<string>("ProductEntityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("DisplayPriority")
                                .HasColumnType("int");

                            b1.HasKey("ProductEntityId", "Id");

                            b1.ToTable("ImageEntity");

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityId");
                        });

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.SearchEntity", b =>
                {
                    b.HasOne("Marketplace.Persistence.Browsing.UserEntity", "User")
                        .WithMany("Searches")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.ViewEntity", b =>
                {
                    b.HasOne("Marketplace.Persistence.Browsing.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Marketplace.Persistence.Browsing.SearchEntity", "Search")
                        .WithMany()
                        .HasForeignKey("SearchId");

                    b.HasOne("Marketplace.Persistence.Browsing.UserEntity", "User")
                        .WithMany("Views")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("Search");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Marketplace.Persistence.Browsing.UserEntity", b =>
                {
                    b.Navigation("Searches");

                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
